/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelfareRouteImport } from './routes/welfare'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DonationRouteImport } from './routes/donation'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WelfareRoute = WelfareRouteImport.update({
  id: '/welfare',
  path: '/welfare',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationRoute = DonationRouteImport.update({
  id: '/donation',
  path: '/donation',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/donation': typeof DonationRoute
  '/gallery': typeof GalleryRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verification': typeof VerificationRoute
  '/welfare': typeof WelfareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/donation': typeof DonationRoute
  '/gallery': typeof GalleryRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verification': typeof VerificationRoute
  '/welfare': typeof WelfareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/donation': typeof DonationRoute
  '/gallery': typeof GalleryRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verification': typeof VerificationRoute
  '/welfare': typeof WelfareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/courses'
    | '/donation'
    | '/gallery'
    | '/pricing'
    | '/sitemap.xml'
    | '/verification'
    | '/welfare'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/courses'
    | '/donation'
    | '/gallery'
    | '/pricing'
    | '/sitemap.xml'
    | '/verification'
    | '/welfare'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/courses'
    | '/donation'
    | '/gallery'
    | '/pricing'
    | '/sitemap.xml'
    | '/verification'
    | '/welfare'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  DonationRoute: typeof DonationRoute
  GalleryRoute: typeof GalleryRoute
  PricingRoute: typeof PricingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerificationRoute: typeof VerificationRoute
  WelfareRoute: typeof WelfareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welfare': {
      id: '/welfare'
      path: '/welfare'
      fullPath: '/welfare'
      preLoaderRoute: typeof WelfareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donation': {
      id: '/donation'
      path: '/donation'
      fullPath: '/donation'
      preLoaderRoute: typeof DonationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  DonationRoute: DonationRoute,
  GalleryRoute: GalleryRoute,
  PricingRoute: PricingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerificationRoute: VerificationRoute,
  WelfareRoute: WelfareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
