/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelfareRouteImport } from './routes/welfare'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DonationRouteImport } from './routes/donation'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WelfareRoute = WelfareRouteImport.update({
  id: '/welfare',
  path: '/welfare',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationRoute = DonationRouteImport.update({
  id: '/donation',
  path: '/donation',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/courses': typeof CoursesRoute
  '/donation': typeof DonationRoute
  '/pricing': typeof PricingRoute
  '/verification': typeof VerificationRoute
  '/welfare': typeof WelfareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/courses': typeof CoursesRoute
  '/donation': typeof DonationRoute
  '/pricing': typeof PricingRoute
  '/verification': typeof VerificationRoute
  '/welfare': typeof WelfareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/courses': typeof CoursesRoute
  '/donation': typeof DonationRoute
  '/pricing': typeof PricingRoute
  '/verification': typeof VerificationRoute
  '/welfare': typeof WelfareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/courses'
    | '/donation'
    | '/pricing'
    | '/verification'
    | '/welfare'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/courses'
    | '/donation'
    | '/pricing'
    | '/verification'
    | '/welfare'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/courses'
    | '/donation'
    | '/pricing'
    | '/verification'
    | '/welfare'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CoursesRoute: typeof CoursesRoute
  DonationRoute: typeof DonationRoute
  PricingRoute: typeof PricingRoute
  VerificationRoute: typeof VerificationRoute
  WelfareRoute: typeof WelfareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welfare': {
      id: '/welfare'
      path: '/welfare'
      fullPath: '/welfare'
      preLoaderRoute: typeof WelfareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donation': {
      id: '/donation'
      path: '/donation'
      fullPath: '/donation'
      preLoaderRoute: typeof DonationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CoursesRoute: CoursesRoute,
  DonationRoute: DonationRoute,
  PricingRoute: PricingRoute,
  VerificationRoute: VerificationRoute,
  WelfareRoute: WelfareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
